export const HOST = "http://localhost:3000"
export const HOST_DB = "mongodb://127.0.0.1"
export const PUERTO_DB = "27017"
export const DB = "Vivahome"
export const SECRET_KEY = "secret-key-vivahome-react"
export const EXPIRED = "30d"